# Generated by Django 5.2.1 on 2025-07-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moradores', '0008_mensagemlida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_visitante', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_agendada', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('entrada_registrada', models.DateTimeField(blank=True, null=True)),
                ('saida_registrada', models.DateTimeField(blank=True, null=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.morador')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porteiro.visita')),
            ],
        ),
    ]
