# Generated by Django 5.1.6 on 2025-03-24 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='categoria',
            field=models.CharField(choices=[('Funcionário', 'Pagamento de Funcionário'), ('Serviços', 'Pagamento de Serviços'), ('Energia', 'Despesas de Energia'), ('Água', 'Despesas de Água'), ('Outro', 'Outro'), ('Pagamento de taxa', 'Pagamento de taxa')], default='Outro', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='is_despesa_condominio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
