# Generated by Django 5.1.6 on 2025-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_casa', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_moradores', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
