# Generated by Django 5.2.1 on 2025-07-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0006_alter_mensagem_assunto_alter_mensagem_data_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='moradores.morador'),
        ),
    ]
