# Generated by Django 5.2.1 on 2025-07-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0007_alter_mensagem_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemLida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.mensagem')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.morador')),
            ],
            options={
                'unique_together': {('morador', 'mensagem')},
            },
        ),
    ]
